const AuthActionType = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    CONFIRM_EMAIL_SUCCESS: "CONFIRM_EMAIL_SUCCESS",
    CONFIRM_EMAIL_FAILURE: "CONFIRM_EMAIL_FAILURE",
    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",
};

const UserActionType = {
    GET_CURRENT_USER_SUCCESS: "GET_CURRENT_USER_SUCCESS",
    GET_CURRENT_USER_FAILURE: "GET_CURRENT_USER_FAILURE",
    SEARCH_USER_SUCCESS: "SEARCH_USER_SUCCESS",
    SEARCH_USER_FAILURE: "SEARCH_USER_FAILURE"
}

const LoadingActionType = {
    SUBMITING: "SUBMITING",
    SUBMITTED: "SUBMITTED"
}

const ConversationActionType = {
    SHOW_CONVERSATIONS_SUCCESS: "SHOW_CONVERSATIONS_SUCCESS",
    SHOW_CONVERSATIONS_FAILURE: "SHOW_CONVERSATIONS_FAILURE",
    ADD_USER_TO_CONVERSATION_SUCCESS: "ADD_USER_TO_CONVERSATION_SUCCESS",
    ADD_USER_TO_CONVERSATION_FAILURE: "ADD_USER_TO_CONVERSATION_FAILURE",
}

const MessageActionType = {
    SHOW_MESSAGES_SUCCESS: "SHOW_MESSAGES_SUCCESS",
    SHOW_MESSAGES_FAILURE: "SHOW_MESSAGES_FAILURE",
    SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
    SEND_MESSAGE_FAILURE: "SEND_MESSAGE_FAILURE"
}

const FileActionType = {
    SEND_FILE_SUCCESS: "SEND_FILE_SUCCESS",
    SEND_FILE_FAILURE: "SEND_FILE_FAILURE",
    UPDATE_AVATAR_SUCCESS: "UPDATE_AVATAR_SUCCESS",
    UPDATE_AVATAR_FAILURE: "UPDATE_AVATAR_FAILURE",
    DOWNLOAD_FILE_SUCCESS: "DOWNLOAD_FILE_SUCCESS",
    DOWNLOAD_FILE_FAILURE: "DOWNLOAD_FILE_FAILURE"
}

export {
    AuthActionType,
    UserActionType,
    LoadingActionType,
    ConversationActionType,
    MessageActionType,
    FileActionType
};